spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: ct123!@#
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/HeroMapper.xml
#  config-location: classpath:mybatis-config.xml